### PR TITLE
Rule for message text validation

### PR DESCRIPTION
**Pull request by cmath10**
Hello! This PR contains a new rule I'd like to add - `valid-message-text`. The main goal &ndash; providing custom validators for messages text, relative to locale. Validators are presumed to be functions with signature:

```typescript
interface Validator {
  (text: string): [boolean, string] // validation result, error text
}
```

Config example (what I actually need in my project):
```javascript
const path = require('path')

module.exports = {
    // ...

    rules: {
        // ...

        '@intlify/vue-i18n/valid-message-text': ['error', {
            validators: {
                'en-GB': [
                    path.join(__dirname, 'eslint/validators/no-old-brand-keywords.js'),
                    path.join(__dirname, 'eslint/validators/no-cyrillic.js'),
                    path.join(__dirname, 'eslint/validators/no-spanish.js'),
                    path.join(__dirname, 'eslint/validators/quotation.js'),
                ],
                'es-ES': [
                    path.join(__dirname, 'eslint/validators/no-old-brand-keywords.js'),
                    path.join(__dirname, 'eslint/validators/no-cyrillic.js'),
                ],
                'ru-RU': [
                    path.join(__dirname, 'eslint/validators/no-old-brand-keywords.js'),
                    path.join(__dirname, 'eslint/validators/no-spanish.js'),
                ],
            },
        }],

        // ...
    },

    // ...
}
```

Validator example (no-cyrillic):
```javascript
module.exports = function (text) {
    const pattern = /([а-яА-Я]+)/g
    const words = []

    let match = pattern.exec(text)

    while (match) {
        words.push(match[1])
        match = pattern.exec(text)
    }

    return [
        words.length === 0,
        words.length !== 0
            ? `Cyrillic symbols found : [${words.map(word => `"${word}"`).join(', ')}]`
            : '',
    ]
}
```

### CODE REVIEW

**Comment by ota-meshi** [comment]
Thank you for PR.
But I still don't want to add that rule.
There are many necessary processes such as morphological analysis to check the validity of the text. Perhaps you need another specialized plugin to implement them.

**Comment by cmath10** [comment]
@ota-meshi, thanks for the response. But I can't understand, why I need another plugin if I need to verify messages, prepared for vue-i18n (especially for i18n custom blocks in SFC)? For my reason, it is not logical. If I need to create another eslint plugin, it will be quite similar to this one (50% of code at least I suppose). If some reworks are required, I opened to discussion.

**Comment by cmath10** [comment]
I use the plugin in CI pipelines, and my team uses the rule I proposed (currently we switched to my fork) to prevent merging branches, where texts violate our internal standards.

**Comment by ota-meshi** [comment]
What specific checks did you do? I'm not sure how useful this rule would be for the test case you added.
I think it needs a lot of additional packages to check if the text is correct as my language (Japanese), so I think it needs to be a separate plugin so that users can opt out of them.

**Comment by cmath10** [comment]
I don't check grammar or something, just:
* unallowed words (old brand, to be sure all old terms are not in use);
* mixed characters - latin & cyrillyc, for example, have 'c', 'a' and some others;
* some other checks, which are quite lightweight (not sure I'm allowed to say which is exactly they are).

In any case, the plugin contains logic that will be needed in any other plugin designed to validate vue-i18n messages - loading & processing ast for example. A hypothetical package that would deal with spell checking in vue-i18n messages would have to share that logic. In addition, the rule that I proposed just allows you to integrate external code, my validators lies in my project repository and they are not part of the rule, they are already pluggable.

**Comment by cmath10** [comment]
It seems I can see your point - my validators are not included in PR, it is just an example of external modules that are dynamically imported

**Comment by ota-meshi** [comment]
> In addition, the rule that I proposed just allows you to integrate external code, my validators lies in my project repository and they are not part of the rule, they are already pluggable.

I think this means that the new rule doesn't work on its own.
In other words, I think it would be more useful for users to provide another ESLint plugin.
If you use a package for plugging valid-message-text for each language, the setting becomes complicated. Because the ESLint rule configuration is not merged.
If you use the eslint plugin for each language, the setup is simple. I think the ESLint shareable configuration for each language will be merged.

> In any case, the plugin contains logic that will be needed in any other plugin designed to validate vue-i18n messages

The vue-i18n plugin may make it easier to create new ESLint plugins by exposing some APIs to the outside.

**Comment by ota-meshi** [comment]
> my validators lies in my project repository

I think it's most valuable to users to make your validator available to all users.

**Comment by cmath10** [comment]
> I think it's most valuable to users to make your validator available to all users.

Mixed characters check maybe could be shared, others are specific to my project

> I think this means that the new rule doesn't work on its own.

It simply an entrypoint for pluggable validators.

> If you use a package for plugging valid-message-text for each language, the setting becomes complicated. Because the ESLint rule configuration is not merged.
If you use the eslint plugin for each language, the setup is simple. I think the ESLint shareable configuration for each language will be merged.

Not sure I understood well, could I ask to illustrate with examples?

**Comment by ota-meshi** [comment]
> Mixed characters check maybe could be shared, 

I'm not sure about Mixed characters, but I think it's a good idea to create and publish a rule to do the same check.

> others are specific to my project

I think that means this rule can only be used by your team. You need to create a unique eslint plugin for your team.

> It simply an entrypoint for pluggable validators.

ESLint already has a mechanism to plug rules by creating an ESLint plugin. No new entry point is needed.

> Not sure I understood well, could I ask to illustrate with examples?

If you use the following two sharable configurations, they will conflict and be overwritten.

```js
{
  rules: {
        '@intlify/vue-i18n/valid-message-text': ['error', {
            validators: {
                'en-GB': [
                    path.join(__dirname, 'eslint/validators/no-old-brand-keywords.js'),
                ]
            },
        }],
  }
}
```

```js
{
  rules: {
        '@intlify/vue-i18n/valid-message-text': ['error', {
            validators: {
                'ru-RU': [
                    path.join(__dirname, 'eslint/validators/no-old-brand-keywords.js'),
                ],
            },
        }],
  }
}
```

If created as separate rules, they will be merged.


```js
{
  rules: {
        'rule-for-en-gb': 'error'
  }
}
```

```js
{
  rules: {
        'rule-for-ru-ru': 'error'
  }
}
```

**Comment by cmath10** [comment]
> I think that means this rule can only be used by your team. You need to create a unique eslint plugin for your team.

The rule can be used anywhere - if you need to check messages texts, validators could contain any validation logic you need. My validators could be replaced.

**Comment by ota-meshi** [comment]
If you can write validation logic, you can do the same by creating an ESLint plugin.

**Comment by cmath10** [comment]
> ESLint already has a mechanism to plug rules by creating an ESLint plugin. No new entry point is needed.
Well, I still need the logic of loading & processing AST.

**Comment by ota-meshi** [comment]
> I still need the logic of loading & processing AST.

Of course it is. But you can also copy the source code for this project.

**Comment by cmath10** [comment]
> Of course it is. But you can also copy the source code for this project.
I already did it. And actually this a thing I tried to avoid.

**Comment by ota-meshi** [comment]
Why do you want to avoid it? The source code for this project is open under the MIT license.

**Pull request closed without merging**
