### PR TITLE
Replace documentation example with `vue-eslint-editor`

### LINKED ISSUE #4: replace documentation example with `eslint-playground` component

### PR DESCRIPTION
**Pull request by ota-meshi**
close #4

### CODE REVIEW

**Comment by ota-meshi** [comment]
Hi @kazupon!
Perhaps we need to change the netlify settings and use `npm run docs:build` for the build.
Can you change the settings when you have time?

**Comment by kazupon** [comment]
@ota-meshi 
I've just changed!
image

**Comment by ota-meshi** [comment]
@kazupon Thank you! I can see the preview now.

https://deploy-preview-153--heuristic-haibt-5d042e.netlify.app/rules/no-missing-keys.html

**Comment by kazupon** [comment]
@ota-meshi 
Wow, vue-eslint-editor is cool!

**Pull request merged**
